const path = require('path');
const fs = require('fs');
const { resolveModule } = require('./resolve-module');

const DIR_NDS = __dirname;
const DIR_NDS_MODULES = path.resolve(DIR_NDS, 'node_modules');

let _project = '.';

function eject$rds_loader_js() {
    const $babel_loader = {
        "loader": resolveModule('babel-loader'),
        "options": {
            "plugins": [
                resolveModule('@babel/plugin-proposal-class-properties'),
            ],
            "presets": [
                [
                    resolveModule('@babel/preset-env'),
                    {
                        "targets": {
                            "esmodules": true
                        }
                    }
                ],
                [
                    resolveModule('@babel/preset-typescript'),
                ],
                [
                    resolveModule('@babel/preset-react'),
                ],
            ]
        }
    };
    const rds_loader_js_export = {
        $babel_loader,
        $css_loader: resolveModule('css-loader'),
        $style_loader: resolveModule('style-loader'),
        $file_loader: resolveModule('file-loader'),
    };
    let comment = `/*\n * Generated by react-dev-server:\n * $ rds --eject\n *\n * @author Develon (https://github.com/develon2015)\n */\n\n`;
    let code = `${comment}module.exports = ${JSON.stringify(rds_loader_js_export, null, 4)};\n`;
    fs.writeFileSync(path.resolve(_project, 'rds-loader.js'), code);
}

/**
 * @deprecated
 */
function eject$babel_config_json() {
    const babel_config_json = {
        "plugins": [
            resolveModule('@babel/plugin-proposal-class-properties'),
        ],
        "presets": [
            [
                resolveModule('@babel/preset-env'),
                {
                    "targets": {
                        "esmodules": true
                    }
                }
            ],
            [
                resolveModule('@babel/preset-typescript'),
            ],
            [
                resolveModule('@babel/preset-react'),
            ],
        ]
    };
    fs.writeFileSync(path.resolve(_project, 'babel.config.json'), JSON.stringify(babel_config_json, null, 2));
}

/**
 * @deprecated
 */
function eject$webpack_config_js() {
    const filename = 'webpack.config.js';
    const webpack_config_js = fs.readFileSync(path.resolve(__dirname, './public/webpack.config.js')).toString('utf-8');
    var replace = webpack_config_js.replace('`@BABEL_LOADER`', JSON.stringify(resolveModule('babel-loader')));
    var replace = replace.replace('`@STYLE_LOADER`', JSON.stringify(resolveModule('style-loader')));
    var replace = replace.replace('`@CSS_LOADER`', JSON.stringify(resolveModule('css-loader')));
    var replace = replace.replace('`@FILE_LOADER`', JSON.stringify(resolveModule('file-loader')));
    fs.writeFileSync(path.resolve(_project, filename), replace);
}

/**
 * @deprecated
 */
function eject$tsconfig_json() {
    const filename = 'tsconfig.json';
    const tsconfig_json = fs.readFileSync(path.resolve(__dirname, './public/tsconfig.json.template')).toString('utf-8');
    fs.writeFileSync(path.resolve(_project, filename), tsconfig_json);
}

function eject(project = process.cwd()) {
    _project = project;
    console.info('弹出配置文件！');
    /* Warn: 不可移植的代码！*/ /*
    eject$babel_config_json();
    eject$webpack_config_js();
    eject$tsconfig_json(); */
    eject$rds_loader_js();
}

module.exports = eject;
